server:
  port: 8080
  servlet:
    context-path: /transaction
    
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false       
  datasource:
#    url: jdbc:mysql://localhost:3306/aqcio?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#p/ Docker   url: jdbc:mysql://mysql:3306/aqcio?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:hsqldb:file:./database_in_memory/aqcio
    username: root
    password: Rr123
    driver-class-name: org.hsqldb.jdbcDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: hsql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:
    name: Acqio
  jmx:
    enabled: false
  