version: '2.1'

services:
  api_acqio:
    image: rodrigotenorio86/acqio_api_rest
    container_name: api
    ports:
      - "8080:8080"
    restart: on-failure:6 
    links:
      - mysql
    depends_on:
        mysql:
            condition: service_healthy      
  mysql:
    image: rodrigotenorio86/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: Rr123
       MYSQL_USER: root
       MYSQL_DATABASE: aqcio
       MYSQL_PASSWORD: Rr123
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10